## Este es el notebook donde haremos todo el procesamiento del modelo de machine learning

In [21]:
# imports
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
dataset = pd.read_csv("../datasets/medical_insurance.csv")

dataset.head()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [32]:
dataset.describe().loc[["count", "mean", "min", "max"]]

,person_id,age,income,household_size,dependents,bmi,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
count,100000.0,100000.0000,100000.000,100000.0000,100000.00000,100000.000000,100000.00000,100000.00000,100000.00000,100000.00000,...,100000.00000,100000.00000,100000.00000,100000.00000,100000.00000,100000.00000,100000.00000,100000.00000,100000.00000,100000.0000
mean,50000.5,47.5215,49873.905,2.4309,0.89838,26.990512,1.92765,0.09364,0.37335,1.23632,...,0.01477,0.10831,0.13014,0.50853,0.15869,0.50839,0.50933,0.50914,0.36781,0.1697
min,1.0,0.0000,1100.000,1.0000,0.00000,12.000000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.0000
max,100000.0,100.0000,1061800.000,9.0000,7.00000,50.400000,25.00000,3.00000,21.00000,11.00000,...,1.00000,1.00000,1.00000,7.00000,6.00000,7.00000,7.00000,7.00000,1.00000,1.0000

In [34]:
dataset.isna().sum()

person_id                          0
age                                0
sex                                0
region                             0
urban_rural                        0
income                             0
education                          0
marital_status                     0
employment_status                  0
household_size                     0
dependents                         0
bmi                                0
smoker                             0
alcohol_freq                   30083
visits_last_year                   0
hospitalizations_last_3yrs         0
days_hospitalized_last_3yrs        0
medication_count                   0
systolic_bp                        0
diastolic_bp                       0
ldl                                0
hba1c                              0
plan_type                          0
network_tier                       0
deductible                         0
copay                              0
policy_term_years                  0
policy_changes_last_2yrs           0
provider_quality                   0
risk_score                         0
annual_medical_cost                0
annual_premium                     0
monthly_premium                    0
claims_count                       0
avg_claim_amount                   0
total_claims_paid                  0
chronic_count                      0
hypertension                       0
diabetes                           0
asthma                             0
copd                               0
cardiovascular_disease             0
cancer_history                     0
kidney_disease                     0
liver_disease                      0
arthritis                          0
mental_health                      0
proc_imaging_count                 0
proc_surgery_count                 0
proc_physio_count                  0
proc_consult_count                 0
proc_lab_count                     0
is_high_risk                       0
had_major_procedure                0
dtype: int64

In [35]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  object
 3   region                       100000 non-null  object
 4   urban_rural                  100000 non-null  object
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  object
 7   marital_status               100000 non-null  object
 8   employment_status            100000 non-null  object
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  object
 13  alcohol_freq                 69917 non-null   object
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  object
 23  network_tier                 100000 non-null  object
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), object(10)
memory usage: 41.2+ MB

In [ ]:
dataset["alcohol_freq"][dataset["age"] < 21]

3               NaN
59       Occasional
78       Occasional
83           Weekly
89              NaN
            ...
99877    Occasional
99927         Daily
99988           NaN
99990           NaN
99991    Occasional
Name: alcohol_freq, Length: 4606, dtype: object

In [42]:
dataset["alcohol_freq"].unique()

array([nan, 'Weekly', 'Daily', 'Occasional'], dtype=object)